name: Build

on:
  release:
    types: 
      - created

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          use_vue_cli: true
          skip_build: true
          github_token: GH_TOKEN
          release: true
